### PR TITLE
Message Edit Support.

### PR DESCRIPTION
**Pull request by Animeshz**
This PR include:

  * Adds inline [KordEventAdapter](https://github.com/Animeshz/kordx.commands/commit/37b38af05042a009d732eea5dfa5be02bfcf760c/kordx-commands-runtime-kord/src/main/kotlin/com/gitlab/kordlib/kordx/commands/kord/model/processor/KordEventAdapter.kt) class, for unifying the Kord Events (MessageCreateEvent and MessageUpdateEvent).

  * Adds support for invocation of command on message edits.

  * Adds [CommandCache](https://github.com/Animeshz/kordx.commands/commit/37b38af05042a009d732eea5dfa5be02bfcf760c/kordx-commands-runtime/src/main/kotlin/com/gitlab/kordlib/kordx/commands/model/cache/CommandCache.kt) for data transfer between first/prior run and current command invocation, with [test](https://github.com/Animeshz/kordx.commands/commit/37b38af05042a009d732eea5dfa5be02bfcf760c/kordx-commands-runtime/src/test/kotlin/com/gitlab/kordlib/kordx/commands/argument/pipe/CommandsTest.kt) and [an example](https://github.com/Animeshz/kordx.commands/commit/37b38af05042a009d732eea5dfa5be02bfcf760c/kordx-commands-runtime-kord/src/test/kotlin/commands/example/CommandCache.kt).

    - CommandCache is conservative in nature, i.e. it is only instantiated and stored into the cache when execution block in `CommandBuilder.invoke(args...) {args..., cache -> }` takes exactly one more parameter than args passed.

    - If caching is not registered in bot configuration (as `bot { registerCommandCache() }`), a ConstantDisabledCache (singleton) is provided.

  * Adds support for edit of argument (KordEventAdapter#read) if previously failed (with ArgumentResult.Failure) or filtered, with [test](https://github.com/Animeshz/kordx.commands/commit/37b38af05042a009d732eea5dfa5be02bfcf760c/kordx-commands-runtime-kord/src/test/kotlin/com/gitlab/kordlib/kordx/commands/kord/argument/KordEventAdapterTest.kt).

  * Adds [same inline reply](https://github.com/kordlib/kord/commit/6eb3f753f545209a812666e43f10114bd8b33d77) as kord 0.7.x to the KordEvent, allowing ease to directly reply to the message on KordCommandEvent.

  * Few minor changes such as:

    - Extracted KordEvent#read to KordEventAdapter#read due to the frequent use of KordErrorHandler (which was instantiating anonymous object on each call), KordEvent#read is still present but is delegated to KordEventAdapter#read.

    - Refactor Arguments to use KordEventAdapter as their context.

    - Refactor PrefixRules to use KordEventAdapter as their context.

  * Migrates deprecated github action [similar to kord](https://github.com/kordlib/kord/commit/bc270f61f6596d0271b8cbc83286cb98a15c1ceb)

### CODE REVIEW

**Comment by BartArys** [comment]
This is a lot of code to make sense of, so I'll just be writing up some questions about rationale as I go, if you don't mind: 

#### KordEventAdapter 
* Why make KordEventAdapter inline at all? It's used in so many generic contexts, won't wrapping and unwrapping the object that many times not be a cause of performance issues instead of gains?
* Why provide a constructor that accepts such a broad type of events when we only accept two?

#### CommandCache 
* Why use the Kord cache to store types from another project?
* Why limit the storage of cached values to one?
* When are CommandCache values removed from the cache?
* Is such a weak type safety on the cache okay? There can be considerable time between storage and retrieval, won't this make debugging more difficult?
* Why make the cache optional? What's the point of storing stuff if it's not consistently present on the next edit?

**Comment by Animeshz** [comment]
**KordEventAdapter**

> Why make KordEventAdapter inline at all? It's used in so many generic contexts, won't wrapping and unwrapping the object that many times not be a cause of performance issues instead of gains?

Welp, I have to rethink about it. Making it non-inline seems a good idea here :)

> Why provide a constructor that accepts such a broad type of events when we only accept two?

[`Flow<Event>.filterAndMapToAdapter()`](https://github.com/Animeshz/kordx.commands/blob/features/message-edit-support/kordx-commands-runtime-kord/src/main/kotlin/com/gitlab/kordlib/kordx/commands/kord/model/processor/KordEventAdapter.kt#L231) filters the events. Though I should have made the class non-inlined and with a private or internal constructor. There was no other way of wrapping though, since the Events we want to capture were completely different from each other since they don't have a common interface.

Maybe we can have more discussion on it to make it better?

**CommandCache**

> Why use the Kord cache to store types from another project?

Welp, that's because `kordx-commands-runtime-kord` is an extension to kord.

> Why limit the storage of cached values to one?

That's up to the user to decide, as the cache only stores the reference of the value. He / She may add List or any other type for his own convenience.

> When are CommandCache values removed from the cache?

CommandCache is just an interface. Regarding KordCommandCache, it depends on Kord's cache configuration done by user, already linked to [an example](https://github.com/Animeshz/kordx.commands/commit/37b38af05042a009d732eea5dfa5be02bfcf760c/kordx-commands-runtime-kord/src/test/kotlin/commands/example/CommandCache.kt). As such if lruCache is used it will get removed if maxCapacity has reached and its access was the oldest, if used default cache it won't be removed till max capacity reached by the Map.

> Is such a weak type safety on the cache okay? There can be considerable time between storage and retrieval, won't this make debugging more difficult?

I couldn't think of a better way than this, I firstly thought to provide a generic CommandCache but since the kord.cache seems  to capture each generic type as a concrete type I couldn't make use of it.

Maybe we can discuss it further to make it better?

> Why make the cache optional? What's the point of storing stuff if it's not consistently present on the next edit?

When did cache became optional? It is conservative i.e. for the commands which takes an extra cache parameter. If invoke function has been called with exactly 1 more parameter than the arguments, then cache will always be given to that. While commands which does not need any caching can implicitly tell to not use cache for them at the compile time by taking no extra parameter in the lambda.

**Comment by BartArys** [comment]
> Maybe we can have more discussion on it to make it better?

I suggest making this a sealed class instead, we're needlessly introducing checks where the type system could help us instead. Additionally, making it sealed allows us to specialize the different types.

---

> Welp, that's because kordx-commands-runtime-kord is an extension to kord.

I find this poor reasoning, we're depending on a cache of which we have no control in terms of implementation, we don't even know if the user enabled it. 
If we are going to add this feature, we should manage our own implementation instead.

> That's up to the user to decide, as the cache only stores the reference of the value. He / She may add List or any other type for his own convenience.

This sounds completely insufficient.

> CommandCache is just an interface. Regarding KordCommandCache, it depends on Kord's cache configuration done by user, already linked to an example. As such if lruCache is used it will get removed if maxCapacity has reached and its access was the oldest, if used default cache it won't be removed till max capacity reached by the Map.

This highlights another problem I brought up, if we're using a LRU cache then we cannot guarantee the value to be present. If we try to guarantee the message to be present then we end up with a de facto memory leak.

> When did cache became optional?

It's optional because it does not guarantee being present in the next edit invocation.

> Maybe we can discuss it further to make it better?

`CommandCache` is a misnomer, it's not a cache for commands, it's a way to retain information between invocation of the same command coming from a common source. The concept doesn't translate to non-fora environments. You cannot edit command invocations in a CLI, HTTP call, etc. So if (and when) we support those targets the feature would be dead weight.

To be honest, the whole feature seems to be contrived. The current concept is lacking is both implementation and features. Additionally, this seems trivially easy to introduce by the user themselves. via DI and metadata.

Personally I'd scrap the idea.

**Comment by Animeshz** [comment]
> This sounds completely insufficient.

:(
I mean different command has different purpose, some commands (like for some searching) may only cache the Message or the id of message and channel, some may require caching of previous response and so on. 

> It's optional because it does not guarantee being present in the next edit invocation.

Yes, if the message is like way older and not in cache then bot should just treat it as a new invocation. We cannot store infinite cache in the system, if it doesn't allow to.

> You cannot edit command invocations in a CLI, HTTP call, etc. So if (and when) we support those targets the feature would be dead weight.

Yeah 😅, I have to rethink about this later some day. For now I'm closing this :)

**Pull request closed without merging**
